<a href="https://colab.research.google.com/github/lucasdonizete/RedesNeurais/blob/main/ANN_CIP_deserability_Julho_15_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# bibliotecas usadas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn import preprocessing
from sklearn.metrics import r2_score 
from google.colab import files
from scipy import optimize

In [2]:
# para gerar o grafico no browser
%matplotlib inline

In [3]:
!git clone https://github.com/lucasdonizete/RedesNeurais/
%cd RedesNeurais

fatal: destination path 'RedesNeurais' already exists and is not an empty directory.
/content/RedesNeurais


In [4]:
df=pd.read_csv("DADOS_CIP_TESE.csv")
print(df.head())

  RUN  A  B  C  D    TR    TE   COT   EXP   RED  ENERGY
0   1  1  1  1 -1  4.92  1.87  4.35  5.81  4.87  160.32
1   2  1  1 -1 -1  5.01  2.20  4.43  5.63  5.26  177.95
2   3  1 -1  1  1  5.27  2.28  3.64  5.94  6.01  132.31
3   4 -1  1 -1  1  4.13  2.45  2.79  5.40  5.33   85.86
4   5  1 -1 -1  1  5.60  2.53  4.67  5.22  5.97  147.02


In [5]:
# separa as variáveis dependentes e independentes
X = df[['A','B','C','D']]
y = np.array(df[['TR','TE','COT','EXP','RED','ENERGY']]).reshape(-1,6)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.10, shuffle=True, random_state=3)

In [7]:
scaler_X = preprocessing.MinMaxScaler((-1,1)).fit(X)
scaler_Y = preprocessing.MinMaxScaler((-1,1)).fit(y)

In [8]:
X_train = scaler_X.transform(X)
y_train = scaler_Y.transform(y)

In [9]:
'''
X_train = scaler_X.transform(X_train)
X_test = scaler_X.transform(X_test)
y_train = scaler_Y.transform(y_train)
y_test = scaler_Y.transform(y_test)
'''

'\nX_train = scaler_X.transform(X_train)\nX_test = scaler_X.transform(X_test)\ny_train = scaler_Y.transform(y_train)\ny_test = scaler_Y.transform(y_test)\n'

In [10]:
# define a rede neural 
model = MLPRegressor(solver='lbfgs',activation='tanh',alpha=1e-5,hidden_layer_sizes=(15),
                     random_state=1)

In [11]:
# treina a rede neural
model.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


MLPRegressor(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=15, learning_rate='constant',
             learning_rate_init=0.001, max_fun=15000, max_iter=200,
             momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
             power_t=0.5, random_state=1, shuffle=True, solver='lbfgs',
             tol=0.0001, validation_fraction=0.1, verbose=False,
             warm_start=False)

In [12]:
# usa a rede neural treina em calculos para treino e teste
y_calc_train=model.predict(X_train)
# y_calc_test=model.predict(X_test)

In [13]:
y_train

array([[ 0.17910448, -0.84680851, -0.11111111,  0.184     , -0.49038462,
         0.65278158],
       [ 0.24626866, -0.56595745, -0.06552707, -0.104     , -0.11538462,
         0.89435462],
       [ 0.44029851, -0.49787234, -0.51566952,  0.392     ,  0.60576923,
         0.2689778 ],
       [-0.41044776, -0.35319149, -1.        , -0.472     , -0.04807692,
        -0.36749794],
       [ 0.68656716, -0.28510638,  0.07122507, -0.76      ,  0.56730769,
         0.47053987],
       [ 0.00746269, -0.41276596,  0.0997151 ,  0.024     ,  0.47115385,
        -0.66799123],
       [-0.43283582, -0.03829787,  0.9031339 ,  0.424     ,  0.55769231,
        -0.3373527 ],
       [ 0.00746269, -0.31914894,  1.        , -0.296     ,  0.625     ,
        -0.5143875 ],
       [ 1.        ,  0.62553191,  0.73219373,  0.68      ,  0.60576923,
         0.26335982],
       [ 0.00746269, -1.        ,  0.27065527, -0.84      ,  0.11538462,
        -1.        ],
       [ 0.15671642,  0.27659574,  0.48148148,  0.

In [14]:
y_calc_train

array([[ 1.78069983e-01, -8.47565294e-01, -1.13398049e-01,
         1.86057117e-01, -4.90022528e-01,  6.53573584e-01],
       [ 2.47159699e-01, -5.63334176e-01, -6.60161823e-02,
        -1.04862720e-01, -1.15078463e-01,  8.99466607e-01],
       [ 4.38245175e-01, -4.95288435e-01, -5.14325521e-01,
         3.89077219e-01,  6.06188893e-01,  2.70978210e-01],
       [-4.08826418e-01, -3.54040042e-01, -1.00129837e+00,
        -4.70171685e-01, -4.94498727e-02, -3.70712183e-01],
       [ 6.88629618e-01, -2.86784331e-01,  7.19113236e-02,
        -7.57355573e-01,  5.66192638e-01,  4.68287424e-01],
       [ 7.04684603e-03, -4.11652673e-01,  9.96866392e-02,
         2.38404392e-02,  4.73418507e-01, -6.68618840e-01],
       [-4.33326237e-01, -3.73949505e-02,  9.00802854e-01,
         4.23847756e-01,  5.58911195e-01, -3.31413957e-01],
       [ 7.00940937e-03, -3.21047021e-01,  1.00019865e+00,
        -2.94494419e-01,  6.21733510e-01, -5.17971968e-01],
       [ 7.60862082e-01,  8.53211824e-01,  8.855

In [15]:
# transforma dos dados calculados na forma original (nao normatizado)
y_obs_train=scaler_Y.inverse_transform(np.array(y_train).reshape(-1,6))
# y_obs_test=scaler_Y.inverse_transform(np.array(y_test).reshape(-1,3))
y_calc_train=scaler_Y.inverse_transform(y_calc_train.reshape(-1,6))
# y_calc_test=scaler_Y.inverse_transform(y_calc_test.reshape(-1,3))

In [16]:
'''
mse=mean_squared_error(y_obs_test,y_calc_test)
print("MSE teste=",mse)
R2=r2_score(y_obs_test,y_calc_test)
print("R^2 teste=",R2)
'''

'\nmse=mean_squared_error(y_obs_test,y_calc_test)\nprint("MSE teste=",mse)\nR2=r2_score(y_obs_test,y_calc_test)\nprint("R^2 teste=",R2)\n'

In [17]:
mse=mean_squared_error(y_obs_train,y_calc_train)
print("MSE treino=",mse)
R2=r2_score(y_obs_train,y_calc_train)
print("R^2 treino=",R2)

MSE treino= 0.5117499488229235
R^2 treino= 0.9863695283782086


In [18]:
def RDTR_calc(x_test): #Time     TC     Y  MI    MW
    global Y_OLD,model
    x_test = np.array(x_test).reshape(-1,4)
    y_calc_test=model.predict(x_test)
    y_calc_test =scaler_Y.inverse_transform(y_calc_test.reshape(-1,6))
    y =  y_calc_test[:,0]
    return y
def RDTE_calc(x_test):
    global Y_OLD,model
    x_test = np.array(x_test).reshape(-1,4)
    y_calc_test=model.predict(x_test)
    y_calc_test =scaler_Y.inverse_transform(y_calc_test.reshape(-1,6))
    y =  y_calc_test[:,1]
    return y
def RDCOT_calc(x_test):
    global Y_OLD,model
    x_test = x_test.reshape(-1,4)
    y_calc_test=model.predict(x_test)
    y_calc_test =scaler_Y.inverse_transform(y_calc_test.reshape(-1,6))
    y =  y_calc_test[:,2]
    return y

def Desirability(y,U,T,L):
    if y<L:
        d=0
    if (y>=L)&(y<=T):
        d=(y-L)/(T-L)
    if (y>=T)&(y<+U):
        d=(U-y)/(U-T)
    if (y>U):
        d=0
    return d

In [19]:
def function(x):
    A=x[0]
    B=x[1]
    C=x[2]
    D=x[3]
    RDTR=RDTR_calc(x)
    RDTE=RDTE_calc(x)
    RDCOT=RDCOT_calc(x)
    U=7
    T=6
    L=0
    d1=Desirability(RDTR,U,T,L)
    U=7
    T=6
    L=0
    d2=Desirability(RDTE,U,T,L)
    U=7
    T=6
    L=0
    d3=Desirability(RDCOT,U,T,L)
    fun = (-1)*(d1*d2*d3)**(1/3)
    return fun

In [20]:
bounds = [(-2, 2),(-2, 2),(-2,2),(-2,2)]

Condicoes = optimize.differential_evolution(function,bounds,
                                      init="latinhypercube", # obs: init="random"
                                      maxiter=500, popsize=50,recombination=0.5)

x_opt = Condicoes.x
x_opt =scaler_X.inverse_transform(np.array(x_opt).reshape(-1,4))
y_opt =model.predict(x_opt)
y_opt =scaler_Y.inverse_transform(np.array(y_opt).reshape(-1,6))
print(x_opt)
print(y_opt)

[[ 0.39916902 -0.06327128 -0.22258857  0.08442039]]
[[  5.66174558   3.79142805   5.90366534   5.97354451   6.26158064
  160.63177554]]



PS: no planejamento de experimentos utilizando o Statistica -e-papers Y=80 MI=65,044 MW=3586,1

tempo=86,65 e Temperatura=178,77